name: TestGitHubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/cache@v2
        id: yarn
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-

      - uses: actions/cache@v2
        id: Cypress-cache
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-Cypress-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-Cypress-v1-


      - if: steps.yarn2-cache.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn build

      - run: yarn test:unit

      - run: docker run -d --name mariadb2 -e MARIADB_ROOT_PASSWORD=abcd@1234 -p 33307:3306  mariadb:latest


      - if: steps.go-cache.outputs.cache-hit != 'true'
        run: go get -v -t -u

      - run: go build

      - run: go test -v


      - run: docker exec -i mariadb2  mysql -uroot -pabcd@1234 <<< "create database \`soc-schedule\`"

      - run: docker exec -i mariadb2  mysql -uroot -pabcd@1234 <<< "CREATE TABLE \`soc-schedule\`.\`employee\` (\`id\` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,\`created_at\` DATETIME(3) NULL DEFAULT NULL,\`updated_at\` DATETIME(3) NULL DEFAULT NULL,\`deleted_at\` DATETIME(3) NULL DEFAULT NULL,\`no\` VARCHAR(2) NULL DEFAULT NULL COMMENT '人員編號' COLLATE 'utf8mb4_general_ci',\`name\` LONGTEXT NULL DEFAULT NULL COMMENT '人員姓名' COLLATE 'utf8mb4_general_ci',\`password\` LONGTEXT NULL DEFAULT NULL COMMENT '人員密碼' COLLATE 'utf8mb4_general_ci',\`is_admin\` TINYINT(1) NULL DEFAULT '0' COMMENT '是否為管理者',\`status\` TINYINT(3) UNSIGNED NULL DEFAULT '1' COMMENT '人員狀態 0啟用 1停用',PRIMARY KEY (\`id\`),INDEX \`欄位 4\` (\`deleted_at\`),UNIQUE INDEX \`欄位 5\` (\`no\`))COLLATE='utf8mb4_general_ci';"

      - run: docker exec -i mariadb2  mysql -u root -p abcd@1234 <<< "CREATE TABLE \`soc-schedule\`.\`schedule\` (\`id\` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,\`created_at\` DATETIME(3) NULL DEFAULT NULL,\`updated_at\` DATETIME(3) NULL DEFAULT NULL,\`deleted_at\` DATETIME(3) NULL DEFAULT NULL,\`date\` DATETIME(3) NULL DEFAULT NULL COMMENT '日期',\`day_employee_id\` BIGINT(20) UNSIGNED NULL DEFAULT NULL COMMENT '日班人員主鍵',\`day_on_duty\` DATETIME(3) NULL DEFAULT NULL COMMENT '日班簽到',\`day_off_duty\` DATETIME(3) NULL DEFAULT NULL COMMENT '日班簽退',\`night_employee_id\` BIGINT(20) UNSIGNED NULL DEFAULT NULL COMMENT '小夜人員主鍵',\`night_on_duty\` DATETIME(3) NULL DEFAULT NULL COMMENT '小夜簽到',\`night_off_duty\` DATETIME(3) NULL DEFAULT NULL COMMENT '小夜簽退',\`graveyard_employee_id\` BIGINT(20) UNSIGNED NULL DEFAULT NULL COMMENT '大夜人員主鍵',\`graveyard_on_duty\` DATETIME(3) NULL DEFAULT NULL COMMENT '大夜簽到',\`graveyard_off_duty\` DATETIME(3) NULL DEFAULT NULL COMMENT '大夜簽退',PRIMARY KEY (\`id\`),INDEX \`deleted_at\` (\`deleted_at\`),UNIQUE INDEX \`date\` (\`date\`))COLLATE='utf8mb4_general_ci';"
      

      - run: ./test-githubaction&

      - run: yarn cypress run -e host=http://127.0.0.1:3001 --config video=false

      - run: docker build --pull --rm -f "Dockerfile" -t testgithubaction:latest "."

      - run: docker save testgithubaction:latest -o testgithubaction.tar

      - run: gzip testgithubaction.tar

      - uses: actions/upload-artifact@v2
        with:
          path: testgithubaction.tar.gz
