name: TestGitHubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/cache@v2
        id: yarn2-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-

      - uses: actions/cache@v2
        id: Cypress-cache
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-Cypress2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-Cypress2-


      - if: steps.yarn2-cache.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn build

      - run: yarn test:unit

      - if: steps.go-cache.outputs.cache-hit != 'true'
        run: go get -v -t -u

      - run: go build

      - run: go test -v

      - run: ./test-githubaction&

      - run: yarn cypress run -e host=http://127.0.0.1:3001 --config video=false

      - run: docker build --pull --rm -f "Dockerfile" -t testgithubaction:latest "."

      - run: docker save testgithubaction:latest -o testgithubaction.tar

      - run: gzip testgithubaction.tar

      - uses: actions/upload-artifact@v2
        with:
          path: testgithubaction.tar.gz
